language: node_js
node_js:
  - 8
branches:
  only:
    - master
before_install:
  - chmod 0777 ./scripts -R
  - npm config set //registry.npmjs.org/:_authToken $NPM_API_KEY
install:
#- yarn --version
#- yarn install --non-interactive
script:
  - npm test && npm run ci:docs
deploy:
  - provider: npm
    email: luke@c2cschools.com
    skip_cleanup: true
    api_key: "$NPM_API_KEY"
    on:
      all_branches: true
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: developer.c2cs.io
    skip_cleanup: true
    acl: public_read
    default_text_charset: utf-8
    region: us-east-1
    upload-dir: docs/source/core-model
    local_dir: docs/html
    on:
      all_branches: true
env:
  global:
    # NPM_API_KEY
    - secure: "FNbKv7ZYvrKFFWNKhPA3z+xGOAqL7K22SWW4LjjBHfwiAw9ljVTczSKqTfLMqWN8l70vcx0L0achRfQp2Cvb+l43x19TIb3KvgQj9SwHnq76sFGvNT94raQZbek31qb6RfNtaNA4n1+53TIa8ikxOdH2lfNYYlAtsL4Y/ntBUZohWYHJ2qZr2Ko0BqyC8Vy+0noaIRQFIAn8cxZeo6YfxeH5PfKxtnTRojLXR7VDYUsMmYsFtfQagGToiGSYDwG/RxwBmDG0ZHHcdMRBhSApSPTc1LVsZCLLfhSTEy1/abc2l5uDjFU1LyuW/YE1OuZuJZ63KytNvkv+13p5qFzXKEkcF3FIKCxJd7MYq4knamNQR53s3r/997b1C+bskiEEgeJquKNQ5p7KAylbPKZnLc9irSGBIcwi6zpDmSV/UVOye3gwFZLne7SRhEVM5CEjNAo1kL+4qWIW9ZdIfpDs+ud39wda/dPlR1ycwaSFMh2D79N9Q0QtbQ6rxfc4rWqRfgX5JXc9/myu92A+J8WiuBF0c1Ld1dKUVye7e69V9rmPzU8/ijJeo7bfLQS4KI0GAF8Z1bP6X+A2AWt0vaqjHRlkFyU12jvSuXSVuLl7aNu2Fe6u1ctnKamMyxMtUeOQdaYbk1zW3nhpTeRdr1j40P+vEjBBf1WLTD9grX23J1E="
    # AWS_ACCESS_KEY_ID
    - secure: "lWDtT2W/OvJYXdf79HLZc8z7Ua+qJhmC7WEkmTItkPO4rPOPfLtfuQm1Kz66FpmFAHQAfPcaLlBqEB72EvS9UtXdn1nPBmRcn0KBgSwmLlBl3mGF8RYX1v/Qm1OZxiJIt7iCFaWouQm6VjnWLKY3NepSwzZyFZzDfn3p3fQpIfA0aoCTKpGObpUAsGXi5jxhrsqMLyL0lO9ygdCzRj5u+duwq6Tg9vPNzkPicaZR00FVBBq8UfZLbWzJSUck567L7JIcLFUG1i7KyZPRJ9GxbFu3tASOYo8bnQbt7TiGOM+yIFDfvHXJEqt9TXrOZmoAGPuPRPDDMYchD63OwNEi1/aIV5ccC/BkTnuLCTkC5MaP4aQ2IEQzw45uwFw/yqgnQYxzqc//1q5z0JEF+dhkRr89WqpOznHUnc9bZjPFNKlyryCo5rE4nHsHY2bEBTDVbv5RwF3P6jya6CsDAJvPaFtJxY78w6AoqDkbNG9FKF9cC0PZ85aYvjls0SFm8nvrYHrRbov7690zYnVYP2Pqwc8DFWKo8L/RP4fjX9/9LzH7Y2EVtASauvwJ37Gpz/AZIpDBiFP00a4rDIfIHX/eT/KcpUcuuaH1LquGhOTf+zrWLpcZV3tP1XUoyPKvP2YjdVQGKJ5atsTRlSjgxQkBjtIOcA6IC+GJbX5mBzVoCxg="
    # AWS_SECRET_ACCESS_KEY
    - secure: "DRRcDFEupFzZWbCUFXmyADGmtQaecoVYNJhHsCsj9jvyJMfrkQUIkMitp7w+LiN4d8QuHPDzctQaRP7IavZAfvCiIMHDd9WhZxty12t0/JoiLXrQSAHL8nkIIqYsR6U+qCVJIEeJx3I1kCbZ566JMKbZH6hvwjnRWUDLchJlalemXFnx5tv4FyUryi5W35QcwG2jFi/RhbLqtIyJpU0GqLFbOctgcegcDzTlHkF+lrFNv3Ko3GjFRK2Cxg1hU+oSR2HThTHEPnfe0VviYPiw4Z5gEoZm/s4KtclACv/Fr0jU7cnLSDVneMVt+8he8Wb0SGhuEldHJf3Gh7LNg9bQf8E+9s5S//FoVTrabw2QA844vLjeDGW0cInSrHkgxvYEfIzAfcd3xabx3ZBeBcrgqHurx3yzru4B5CU8SLE6OtsJsJQca0bJi6SH+/hKftkf53xr/AsPxktX3jRFaOvFwO9bS+OS6+isweclNhFDQW1dhypuAXJvGh7gptevsASXgSDM4pNAahOuNRzZDXwqxk+sQD0tyKyKDyjdfvBgyKxkr0Q1X+Qgy420nxoFw9obkPJqyPt+Wdn/RXJEiDQyq2/eeKgvIA9hhSHGNoGUg5CNRhmY3iqKBWzeVh8/bpNTAY5fD4ZNIKN48Soha9jQJxNTOGy1bz6oTMWWmjGPGX0="
notifications:
  slack:
    secure: "Zc/m28DJVww0FRZaA0DqSZWNq8a4nOoXFhvbeWQ35cmcUscnNVshHI0k3QM5ZGzPNLSmywCf5coanHOyYA5wlwbtM8gtncHh0GZnyOfOZk3SYgW5mX0d0hcF7iZlZDbYNEiiw+eRMXJNi/2Yq49iHFRA7pRLrtuHWxQ/pTMOo1JSxH8WGeBYyf8N7+pkzAjw7p0F90RBfFR9AyFXzD/qXK1GVzhlZGU86uvuLt4yV4ljkcIYPlN2eYHphzVBbBzoMzG/HQbyvmYwQks93nWhJLBWFpcPAcgWky8w3t3FnPQS4oEhU+5SxR+BV6KE6yO2sRDzGKnzePtx6xpJF10TThr4oM4SR7Hk4Ms+2LMeyYzTv2Ba11U/xv/aMZf3umgSh/yg80XI9miRMVT0PirB886ti9Uf7keah7Sm6DAbAgSf9Gpj1frgjXCSKBZD/+NekzfpqQPjE6ZugyY+XQ1/LYVXU2t6Kbv60Nx2vmS8mkjG8nITB97h3SVqk8Rm3ozIZBVC3Y4uj/cpelj8VaTV9IqOILuTLCTtKlLRFWtWBTxvwqoSU8lFiLWaBwXEJeKEkSsWuTMW+ovCgltdJU2BpuuthMGU82Q9mV1eh98VE9Pg85bB618vvzpLQWwMFhv7TIziGhg81ksFJ0SPcG1TAy8Mrcrp72k8fZpGmZmL794="
